# Adds coreos_pkg_home/bin to PATH environment variable
- name: Add {{ coreos_pkg_home }}/bin to PATH environment variable
  include: add_python_to_PATH.yml

# Generates the cloud-config and pushes into the server
- name: Generate cloud-config
  include: cloud_config.yml

