# Adds coreos_pkg_home/bin to PATH environment variable
- name: Add {{ coreos_pkg_home }}/bin to PATH environment variable
  include: add_python_to_PATH.yml

# Generates the cloud-config and pushes into the server
#- name: Generate cloud-config
#  include: cloud_config.yml

# Adds daemon.json to allow workers access registry
#- name: Configure docker daemon.json file
#  template:
#    src: '{{ docker_daemon_options | to_nice_json }}'
#    dest: /etc/docker/daemon.json
#    mode: 0644
#  notify: restart docker
