# Bootstrap Ansible for CoreOS:
#   - Create /opt/apptv directory
#   - Install PyPy (portable Python implementation), pip and dependencies
- name: Ansible bootstraping in CoreOS servers
  hosts: coreos
  gather_facts: False
  roles:
    - coreos_prebootstrap
    - ansible-coreos-bootstrap

# CoreOS configuration:
#   - Add /opt/apptv/bin to PATH environment variable
#   - Generate cloud-config
- name: CoreOS configuration
  hosts: coreos
  roles:
    - coreos

# Docker Compose Setup
# Swarm managers:
#   - Install Docker-compose with pip
- name: docker-compose setup
  hosts: swarm-managers
  serial: 1
  roles:
    - install_docker_compose

# Docker Swarm bootstrap (from v.1.12 onwards)
# Swarm managers:
#   - Cluster init and set manager host as leader
- name: Swarm cluster initialization (at first manager node)
  hosts: swarm-managers[0]
  roles:
    -  role: swarm_node_1_12 

# Swarm workers:
#   - Join swark-workers to the cluster
- name: Add worker nodes (ONLY WORKERS) to Swarm cluster
  hosts: swarm-workers
  become: yes
  become_user: root
  serial: 1
  roles:
    - swarm_node_1_12_workers


# Middleware or internal nodes:
#   - Create directories for Docker containers persistence (under /data)
- name: Middleware or internal nodes (subgroup of CoreOS servers, inside Docker Swarm cluster)
  hosts: coreos-middlewares
  become: yes
  become_user: root
  roles:
    - middleware_internal

